### ISSUE TITLE
bertanya

### ISSUE THREAD

**Issue by BOTCAHX** [MatchBox-ID/WhatsApp-OfficialApi#1]
itu masih projek kah bang?

**Comment by MatchBox-ID** [comment]
> itu masih projek kah bang?

Halo @BOTCAHX yah itu masih projek kami masih membuat token untuk whatsapp-api itu tetapi untuk saat ini whatsapp api ini dibiayai berlangganan 30Ribu perbulan Dan fiturnya Pun melimpah

**Comment by BOTCAHX** [comment]
wah semoga cepat rilis :)
